from app import app, db, models, bcrypt

#initialise locations
location = models.collection_point(location = 'Trinity Centre', num_scooters = 0)
db.session.add(location)
location = models.collection_point(location = 'Train Station', num_scooters = 0)
db.session.add(location)
location = models.collection_point(location = 'Merrion Centre', num_scooters = 0)
db.session.add(location)
location = models.collection_point(location = 'LRI Hospital', num_scooters = 0)
db.session.add(location)
location = models.collection_point(location = 'UoL Edge Sports Centre', num_scooters = 0)
db.session.add(location)

#initialise pricing
pricing = models.pricing(duration = "1 Hour", price = 10.00)
db.session.add(pricing)
pricing = models.pricing(duration = "4 Hours", price = 39.00)
db.session.add(pricing)
pricing = models.pricing(duration = "1 Day", price = 109.00)
db.session.add(pricing)
pricing = models.pricing(duration = "1 Week", price = 399.00)
db.session.add(pricing)

#initialise scooters
scooter = models.scooter(id = 100, availability = 1, collection_id = 1)
db.session.add(scooter)
scooter = models.scooter(id = 101, availability = 1, collection_id = 1)
db.session.add(scooter)
scooter = models.scooter(id = 102, availability = 1, collection_id = 1)
db.session.add(scooter)
scooter = models.scooter(id = 103, availability = 1, collection_id = 1)
db.session.add(scooter)

scooter = models.scooter(id = 104, availability = 1, collection_id = 2)
db.session.add(scooter)
scooter = models.scooter(id = 105, availability = 1, collection_id = 2)
db.session.add(scooter)
scooter = models.scooter(id = 106, availability = 1, collection_id = 2)
db.session.add(scooter)
scooter = models.scooter(id = 107, availability = 1, collection_id = 2)
db.session.add(scooter)

scooter = models.scooter(id = 108, availability = 1, collection_id = 3)
db.session.add(scooter)
scooter = models.scooter(id = 109, availability = 1, collection_id = 3)
db.session.add(scooter)
scooter = models.scooter(id = 200, availability = 1, collection_id = 3)
db.session.add(scooter)
scooter = models.scooter(id = 201, availability = 1, collection_id = 3)
db.session.add(scooter)

scooter = models.scooter(id = 202, availability = 1, collection_id = 4)
db.session.add(scooter)
scooter = models.scooter(id = 203, availability = 1, collection_id = 4)
db.session.add(scooter)
scooter = models.scooter(id = 204, availability = 1, collection_id = 4)
db.session.add(scooter)
scooter = models.scooter(id = 205, availability = 1, collection_id = 4)
db.session.add(scooter)

scooter = models.scooter(id = 206, availability = 1, collection_id = 5)
db.session.add(scooter)
scooter = models.scooter(id = 207, availability = 1, collection_id = 5)
db.session.add(scooter)
scooter = models.scooter(id = 208, availability = 1, collection_id = 5)
db.session.add(scooter)
scooter = models.scooter(id = 209, availability = 1, collection_id = 5)
db.session.add(scooter)

db.session.commit()

#initialise user
user = models.user(name ="Normal User", email="test@gmail.com", account_type="customer", user_type="default", password=bcrypt.generate_password_hash("test"))
student = models.user(name ="Student", email="student@gmail.com", account_type="customer", user_type="student", password=bcrypt.generate_password_hash("test"))
senior = models.user(name ="Senior", email="senior@gmail.com", account_type="customer", user_type="senior", password=bcrypt.generate_password_hash("test"))
employee = models.user(name ="Employee", email="employee@gmail.com", account_type="employee", user_type="default", password=bcrypt.generate_password_hash("test"))
manager = models.user(name ="Manager", email="manager@gmail.com", account_type="manager", user_type="default", password=bcrypt.generate_password_hash("test"))
db.session.add(user)
db.session.add(employee)
db.session.add(manager)
db.session.add(student)
db.session.add(senior)
db.session.commit()
